// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY98ze1UuPe7k5_1ZwHrSGKIuXA86YYL8',
    appId: '1:865090002544:web:b80fb186d5ba747950deb5',
    messagingSenderId: '865090002544',
    projectId: 'jmate-ae634',
    authDomain: 'jmate-ae634.firebaseapp.com',
    databaseURL: 'https://jmate-ae634-default-rtdb.firebaseio.com',
    storageBucket: 'jmate-ae634.appspot.com',
    measurementId: 'G-HRKDMEPYPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd8AbmQz8gKuiKnEnUYW7niq2_7BkVvGM',
    appId: '1:865090002544:android:3468252c44d8219350deb5',
    messagingSenderId: '865090002544',
    projectId: 'jmate-ae634',
    databaseURL: 'https://jmate-ae634-default-rtdb.firebaseio.com',
    storageBucket: 'jmate-ae634.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBfVUdzu7WpXPhXneiugmXuGG3fm3fcVE',
    appId: '1:865090002544:ios:88cf94c7a7f13bc750deb5',
    messagingSenderId: '865090002544',
    projectId: 'jmate-ae634',
    databaseURL: 'https://jmate-ae634-default-rtdb.firebaseio.com',
    storageBucket: 'jmate-ae634.appspot.com',
    iosClientId: '865090002544-95fehunhnkj73rsbabkqs0g4nimvm5md.apps.googleusercontent.com',
    iosBundleId: 'com.example.jmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBfVUdzu7WpXPhXneiugmXuGG3fm3fcVE',
    appId: '1:865090002544:ios:88cf94c7a7f13bc750deb5',
    messagingSenderId: '865090002544',
    projectId: 'jmate-ae634',
    databaseURL: 'https://jmate-ae634-default-rtdb.firebaseio.com',
    storageBucket: 'jmate-ae634.appspot.com',
    iosClientId: '865090002544-95fehunhnkj73rsbabkqs0g4nimvm5md.apps.googleusercontent.com',
    iosBundleId: 'com.example.jmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY98ze1UuPe7k5_1ZwHrSGKIuXA86YYL8',
    appId: '1:865090002544:web:a7bdaf850c3ab27f50deb5',
    messagingSenderId: '865090002544',
    projectId: 'jmate-ae634',
    authDomain: 'jmate-ae634.firebaseapp.com',
    databaseURL: 'https://jmate-ae634-default-rtdb.firebaseio.com',
    storageBucket: 'jmate-ae634.appspot.com',
    measurementId: 'G-602RT8S7S7',
  );
}
